export const REALTIME_REDIS_COMMAND_CLIENT = Symbol('REALTIME_REDIS_COMMAND_CLIENT');
export const REALTIME_REDIS_ADAPTER_PUBLISHER = Symbol('REALTIME_REDIS_ADAPTER_PUBLISHER');
export const REALTIME_REDIS_ADAPTER_SUBSCRIBER = Symbol('REALTIME_REDIS_ADAPTER_SUBSCRIBER');
export const REALTIME_REDIS_EVENT_SUBSCRIBER = Symbol('REALTIME_REDIS_EVENT_SUBSCRIBER');
export const REALTIME_SOCKET_IO_ADAPTER_FACTORY = Symbol('REALTIME_SOCKET_IO_ADAPTER_FACTORY');
