export const REALTIME_DATABASE_CONNECTION = Symbol('REALTIME_DATABASE_CONNECTION');
export const REALTIME_DATABASE_CLIENT = Symbol('REALTIME_DATABASE_CLIENT');
export const REALTIME_POSTGRES_POOL = Symbol('REALTIME_POSTGRES_POOL');
