export const DATABASE_CONNECTION = Symbol('DATABASE_CONNECTION');
export const DATABASE_CLIENT = Symbol('DATABASE_CLIENT');
export const DATABASE_SEED_REGISTRY = Symbol('DATABASE_SEED_REGISTRY');
export const POSTGRES_POOL = Symbol('POSTGRES_POOL');
