import type { ApiEnvironment } from '@megaconvert/config';

export function buildTestEnvironment(
  overrides: Partial<ApiEnvironment> = {},
): ApiEnvironment {
  return {
    API_GLOBAL_PREFIX: undefined,
    APP_COMMIT_SHA: null,
    APP_VERSION: '0.1.0-test',
    AUTH_ACCESS_COOKIE_NAME: 'mc_access',
    AUTH_ACCESS_TOKEN_AUDIENCE: 'megaconvert-web-test',
    AUTH_ACCESS_TOKEN_SECRET: 'test-access-token-secret-value-for-auth-suite',
    AUTH_ACCESS_TOKEN_TTL_SECONDS: 300,
    AUTH_GOOGLE_CLIENT_ID: 'google-client-id-test',
    AUTH_GOOGLE_CLIENT_SECRET: 'google-client-secret-test',
    AUTH_GOOGLE_DISCOVERY_URL: 'https://accounts.google.com/.well-known/openid-configuration',
    AUTH_REFRESH_COOKIE_NAME: 'mc_refresh',
    AUTH_REFRESH_TOKEN_TTL_DAYS: 30,
    AUTH_STATE_COOKIE_NAME: 'mc_auth_state',
    AUTH_STATE_COOKIE_TTL_SECONDS: 600,
    AUTH_STATE_SIGNING_SECRET: 'test-state-signing-secret-value-for-auth-suite',
    AUTH_WEB_BASE_URL: 'http://localhost:3000',
    AUDIT_PERSISTENCE_ENABLED: false,
    CORS_ORIGINS: ['http://localhost:3000'],
    DATABASE_APPLICATION_NAME: 'megaconvert-api-test',
    DATABASE_CONNECTION_TIMEOUT_MS: 250,
    DATABASE_IDLE_TIMEOUT_MS: 250,
    DATABASE_POOL_MAX: 2,
    DATABASE_SSL_MODE: 'disable',
    DATABASE_STATEMENT_TIMEOUT_MS: 250,
    DATABASE_URL: 'postgresql://megaconvert:megaconvert@127.0.0.1:5999/megaconvert',
    HOST: '127.0.0.1',
    LOG_LEVEL: 'silent',
    NODE_ENV: 'test',
    PORT: 0,
    PUBLIC_ORIGIN: 'http://127.0.0.1:0',
    RATE_LIMIT_ALLOW_LIST: [],
    RATE_LIMIT_ENABLED: true,
    RATE_LIMIT_GLOBAL_MAX: 100,
    RATE_LIMIT_GLOBAL_WINDOW_SECONDS: 60,
    REALTIME_EVENTS_CHANNEL: 'megaconvert:realtime:events',
    REDIS_KEY_PREFIX: 'megaconvert:test:',
    REDIS_URL: undefined,
    REQUEST_ID_HEADER: 'x-correlation-id',
    RUN_MIGRATIONS_ON_BOOT: false,
    SEED_HOOKS_ENABLED: false,
    SECURITY_HEADERS_ENABLED: true,
    SHUTDOWN_GRACE_PERIOD_MS: 1_000,
    TRUST_PROXY: false,
    ...overrides,
  };
}
